{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "ff63acea",
   "metadata": {},
   "source": [
    "# Parametric model of plate with multiple holes"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "46fdf9e6",
   "metadata": {},
   "source": [
    "### Objective:\n",
    "In this example we'll setup a parametric model in PyMAPDL for a rectangular plate with multiple holes. The model is setup such that one can change the dimensions of the plate, the number of holes and their radius, the material properties and the pressure applied.\n",
    "\n",
    "The learning objectives of this demo are:\n",
    "* Launch PyMAPDL on a local machine\n",
    "* Setup and solve a parametric model using PyMAPDL\n",
    "* Interactive plotting of CAD, mesh, and results in Pythonic interface."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4c801db2",
   "metadata": {},
   "source": [
    "### Model Details\n",
    "<div>\n",
    "    <img src=\"attachment:plate_with_hole.png\" width=\"500\"/>\n",
    "</div>\n",
    "\n",
    "#### Model parameters:\n",
    "* Length, width and depth of the plate\n",
    "* Number of holes\n",
    "* Raidus of the holes\n",
    "* Material properties (Young's modulus and Poisson's ratio)\n",
    "* Applied pressure"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b3708f0d",
   "metadata": {},
   "source": [
    "## Step 1 - define all parameters"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "60b6fc44",
   "metadata": {},
   "outputs": [],
   "source": [
    "# All units in (m, Kg, s)\n",
    "LENGTH = 5\n",
    "WIDTH = 2.5\n",
    "DEPTH = 0.1\n",
    "RADIUS = 0.5\n",
    "NUM = 3\n",
    "\n",
    "E = 2e11\n",
    "NU = 0.27\n",
    "\n",
    "PRESSURE = 1000"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f076d880",
   "metadata": {},
   "source": [
    "# Step 2 - launch MAPDL and create geometry"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "ccaf0f54",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "0a474c42284742d082d60a7cffb57734",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Widget(value='<iframe src=\"http://localhost:61668/index.html?ui=P_0x27b7d6f4fb0_1&reconnect=auto\" class=\"pyvis…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "from ansys.mapdl.core import launch_mapdl\n",
    "mapdl = launch_mapdl()\n",
    "\n",
    "mapdl.clear()\n",
    "mapdl.prep7()\n",
    "mapdl.block(0, LENGTH, 0, WIDTH, 0, DEPTH)\n",
    "for i in range(1,NUM+1):\n",
    "    mapdl.cyl4(i*LENGTH/(NUM+1),WIDTH/2,RADIUS,'','','',2*DEPTH)\n",
    "mapdl.vsbv(1,'all')\n",
    "mapdl.vplot('all')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e8c2af6f",
   "metadata": {},
   "source": [
    "## Step 3 - define material properties, mesh attributes and generate mesh."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "dbef9ba5",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "f9d4c476cf5840e0b18799c7e552763b",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Widget(value='<iframe src=\"http://localhost:61668/index.html?ui=P_0x27b01a66510_2&reconnect=auto\" class=\"pyvis…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "mapdl.lesize(\"ALL\", 0.15, layer1=1)\n",
    "\n",
    "mapdl.mp('ex',1,E)\n",
    "mapdl.mp('nuxy',1,NU)\n",
    "\n",
    "mapdl.et(1,'SOLID186')\n",
    "mapdl.mshape(1, \"3D\")\n",
    "mapdl.mshkey(0)\n",
    "mapdl.vmesh('all')\n",
    "mapdl.eplot()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "49a583cb",
   "metadata": {},
   "source": [
    "## Step 4 - apply loads and boundary conditions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "de8713af",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "***** ROUTINE COMPLETED *****  CP =         0.719"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "mapdl.nsel('s','loc','x',0)\n",
    "mapdl.d('all','all',0)\n",
    "\n",
    "mapdl.nsel('s','loc','x', LENGTH)\n",
    "mapdl.sf('all','pres',PRESSURE)\n",
    "\n",
    "mapdl.allsel()\n",
    "mapdl.finish()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c7e358d5",
   "metadata": {},
   "source": [
    "## Step 4 - solve the static problem"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "06f2eb58",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "FINISH SOLUTION PROCESSING\n",
       "\n",
       "\n",
       " ***** ROUTINE COMPLETED *****  CP =         3.625"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "mapdl.slashsolu()\n",
    "mapdl.solve()\n",
    "mapdl.finish()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "74deb77d-f477-4073-bb53-daecd007c1fa",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "*** NOTE ***                            CP =       3.625   TIME= 16:46:44\n",
      " The automatic domain decomposition logic has selected the MESH domain   \n",
      " decomposition method with 2 processes per solution.                     \n",
      "\n",
      " *****  ANSYS SOLVE    COMMAND  *****\n",
      "\n",
      " *** NOTE ***                            CP =       3.625   TIME= 16:46:44\n",
      " There is no title defined for this analysis.                            \n",
      "\n",
      " *** SELECTION OF ELEMENT TECHNOLOGIES FOR APPLICABLE ELEMENTS ***\n",
      "                ---GIVE SUGGESTIONS ONLY---\n",
      "\n",
      " ELEMENT TYPE         1 IS SOLID186. KEYOPT(2) IS ALREADY SET AS SUGGESTED.\n",
      "\n",
      "\n",
      "\n",
      " *** ANSYS - ENGINEERING ANALYSIS SYSTEM  RELEASE 2022 R1          22.1     ***\n",
      " DISTRIBUTED Ansys Mechanical Enterprise                       \n",
      "\n",
      " 00000000  VERSION=WINDOWS x64   16:46:44  JAN 04, 2024 CP=      3.625\n",
      "\n",
      "                                                                               \n",
      "\n",
      "\n",
      "\n",
      "                       S O L U T I O N   O P T I O N S\n",
      "\n",
      "   PROBLEM DIMENSIONALITY. . . . . . . . . . . . .3-D                  \n",
      "   DEGREES OF FREEDOM. . . . . . UX   UY   UZ  \n",
      "   ANALYSIS TYPE . . . . . . . . . . . . . . . . .STATIC (STEADY-STATE)\n",
      "   GLOBALLY ASSEMBLED MATRIX . . . . . . . . . . .SYMMETRIC  \n",
      "\n",
      " *** NOTE ***                            CP =       3.625   TIME= 16:46:44\n",
      " Present time 0 is less than or equal to the previous time.  Time will   \n",
      " default to 1.                                                           \n",
      "\n",
      " *** NOTE ***                            CP =       3.625   TIME= 16:46:44\n",
      " The conditions for direct assembly have been met.  No .emat or .erot    \n",
      " files will be produced.                                                 \n",
      "\n",
      "  \n",
      "  \n",
      "     D I S T R I B U T E D   D O M A I N   D E C O M P O S E R\n",
      "  \n",
      "  ...Number of elements: 3278\n",
      "  ...Number of nodes:    7036\n",
      "  ...Decompose to 2 CPU domains\n",
      "  ...Element load balance ratio =     1.000\n",
      "\n",
      "\n",
      "                      L O A D   S T E P   O P T I O N S\n",
      "\n",
      "   LOAD STEP NUMBER. . . . . . . . . . . . . . . .     1\n",
      "   TIME AT END OF THE LOAD STEP. . . . . . . . . .  1.0000    \n",
      "   NUMBER OF SUBSTEPS. . . . . . . . . . . . . . .     1\n",
      "   STEP CHANGE BOUNDARY CONDITIONS . . . . . . . .    NO\n",
      "   PRINT OUTPUT CONTROLS . . . . . . . . . . . . .NO PRINTOUT\n",
      "   DATABASE OUTPUT CONTROLS. . . . . . . . . . . .ALL DATA WRITTEN\n",
      "                                                  FOR THE LAST SUBSTEP\n",
      "\n",
      "\n",
      " SOLUTION MONITORING INFO IS WRITTEN TO FILE= file.mntr                                                                                                                                                                                                                                                           \n",
      "\n",
      "\n",
      " Range of element maximum matrix coefficients in global coordinates\n",
      " Maximum = 1.054464748E+11 at element 359.                               \n",
      " Minimum = 8.300811073E+09 at element 1867.                              \n",
      "\n",
      "   *** ELEMENT MATRIX FORMULATION TIMES\n",
      "     TYPE    NUMBER   ENAME      TOTAL CP  AVE CP\n",
      "\n",
      "        1      3278  SOLID186      0.266   0.000081\n",
      " Time at end of element matrix formulation CP = 3.84375.                 \n",
      "\n",
      " DISTRIBUTED SPARSE MATRIX DIRECT SOLVER.\n",
      "  Number of equations =       20769,    Maximum wavefront =    168\n",
      "\n",
      "  Process memory allocated for solver              =    32.299 MB\n",
      "  Process memory required for in-core solution     =    31.072 MB\n",
      "  Process memory required for out-of-core solution =    18.006 MB\n",
      "\n",
      "  Total memory allocated for solver                =    64.242 MB\n",
      "  Total memory required for in-core solution       =    61.787 MB\n",
      "  Total memory required for out-of-core solution   =    35.451 MB\n",
      "\n",
      " *** NOTE ***                            CP =       3.906   TIME= 16:46:44\n",
      " The Distributed Sparse Matrix Solver is currently running in the        \n",
      " in-core memory mode.  This memory mode uses the most amount of memory   \n",
      " in order to avoid using the hard drive as much as possible, which most  \n",
      " often results in the fastest solution time.  This mode is recommended   \n",
      " if enough physical memory is present to accommodate all of the solver   \n",
      " data.                                                                   \n",
      " Distributed sparse solver maximum pivot= 1.238589586E+11 at node 5673   \n",
      " UX.                                                                     \n",
      " Distributed sparse solver minimum pivot= 6697804.76 at node 4513 UZ.    \n",
      " Distributed sparse solver minimum pivot in absolute value= 6697804.76   \n",
      " at node 4513 UZ.                                                        \n",
      "\n",
      "   *** ELEMENT RESULT CALCULATION TIMES\n",
      "     TYPE    NUMBER   ENAME      TOTAL CP  AVE CP\n",
      "\n",
      "        1      3278  SOLID186      0.109   0.000033\n",
      "\n",
      "   *** NODAL LOAD CALCULATION TIMES\n",
      "     TYPE    NUMBER   ENAME      TOTAL CP  AVE CP\n",
      "\n",
      "        1      3278  SOLID186      0.031   0.000010\n",
      " *** LOAD STEP     1   SUBSTEP     1  COMPLETED.    CUM ITER =      1\n",
      " *** TIME =   1.00000         TIME INC =   1.00000      NEW TRIANG MATRIX\n",
      "\n",
      "\n",
      " *** ANSYS BINARY FILE STATISTICS\n",
      "  BUFFER SIZE USED= 16384\n",
      "        4.812 MB WRITTEN ON ASSEMBLED MATRIX FILE: file0.full\n",
      "        2.312 MB WRITTEN ON RESULTS FILE: file0.rst\n"
     ]
    }
   ],
   "source": [
    "# enter the solver routine and solve \n",
    "mapdl.slashsolu()\n",
    "output = mapdl.solve()\n",
    "\n",
    "print(output)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "752c949d",
   "metadata": {},
   "source": [
    "## Step 5 - plot the stress contours for the model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "785360c7",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "c3f48fa093444c328e7b63fb12713f72",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Widget(value='<iframe src=\"http://localhost:61668/index.html?ui=P_0x27b01c30140_3&reconnect=auto\" class=\"pyvis…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "result = mapdl.result\n",
    "result.plot_principal_nodal_stress(0,'seqv',background='w',show_edges=True,text_color='k',add_text=True)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e064eea6",
   "metadata": {},
   "source": [
    "## Step 6 - exit MAPDL"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "c87dedd1",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception raised\n",
      "KeyError('8270614faac5700d37d4f1cb90c6ab25_186d')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\wslink\\protocol.py\", line 332, in onMessage\n",
      "    results = func(*args, **kwargs)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\protocols\\local_rendering.py\", line 33, in get_array\n",
      "    self.context.get_cached_data_array(data_hash, binary)\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\serializers\\synchronization_context.py\", line 35, in get_cached_data_array\n",
      "    cache_obj = self.data_array_cache[p_md5]\n",
      "                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n",
      "KeyError: '8270614faac5700d37d4f1cb90c6ab25_186d'\n",
      "\n",
      "Exception raised\n",
      "KeyError('57dc9e528f6aa5262fa2d0f2ccaf5c5c_150L')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\wslink\\protocol.py\", line 332, in onMessage\n",
      "    results = func(*args, **kwargs)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\protocols\\local_rendering.py\", line 33, in get_array\n",
      "    self.context.get_cached_data_array(data_hash, binary)\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\serializers\\synchronization_context.py\", line 35, in get_cached_data_array\n",
      "    cache_obj = self.data_array_cache[p_md5]\n",
      "                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n",
      "KeyError: '57dc9e528f6aa5262fa2d0f2ccaf5c5c_150L'\n",
      "\n",
      "Exception raised\n",
      "KeyError('4db14661b29a1174a844357dd5a25a15_186d')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\wslink\\protocol.py\", line 332, in onMessage\n",
      "    results = func(*args, **kwargs)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\protocols\\local_rendering.py\", line 33, in get_array\n",
      "    self.context.get_cached_data_array(data_hash, binary)\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\serializers\\synchronization_context.py\", line 35, in get_cached_data_array\n",
      "    cache_obj = self.data_array_cache[p_md5]\n",
      "                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n",
      "KeyError: '4db14661b29a1174a844357dd5a25a15_186d'\n",
      "\n",
      "Exception raised\n",
      "KeyError('541a43fa7d3f990bd8bfbc8152b176bc_150L')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\wslink\\protocol.py\", line 332, in onMessage\n",
      "    results = func(*args, **kwargs)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\protocols\\local_rendering.py\", line 33, in get_array\n",
      "    self.context.get_cached_data_array(data_hash, binary)\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\serializers\\synchronization_context.py\", line 35, in get_cached_data_array\n",
      "    cache_obj = self.data_array_cache[p_md5]\n",
      "                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n",
      "KeyError: '541a43fa7d3f990bd8bfbc8152b176bc_150L'\n",
      "\n",
      "Exception raised\n",
      "KeyError('d054404bf678b64ece94c09d76250416_96d')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\wslink\\protocol.py\", line 332, in onMessage\n",
      "    results = func(*args, **kwargs)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\protocols\\local_rendering.py\", line 33, in get_array\n",
      "    self.context.get_cached_data_array(data_hash, binary)\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\serializers\\synchronization_context.py\", line 35, in get_cached_data_array\n",
      "    cache_obj = self.data_array_cache[p_md5]\n",
      "                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n",
      "KeyError: 'd054404bf678b64ece94c09d76250416_96d'\n",
      "\n",
      "Exception raised\n",
      "KeyError('155d5f9bcf9d0c65078a22d6d0621119_75L')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\wslink\\protocol.py\", line 332, in onMessage\n",
      "    results = func(*args, **kwargs)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\protocols\\local_rendering.py\", line 33, in get_array\n",
      "    self.context.get_cached_data_array(data_hash, binary)\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\serializers\\synchronization_context.py\", line 35, in get_cached_data_array\n",
      "    cache_obj = self.data_array_cache[p_md5]\n",
      "                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n",
      "KeyError: '155d5f9bcf9d0c65078a22d6d0621119_75L'\n",
      "\n",
      "Exception raised\n",
      "KeyError('b849da5de9259d09deb9c1f88c76b73b_96d')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\wslink\\protocol.py\", line 332, in onMessage\n",
      "    results = func(*args, **kwargs)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\protocols\\local_rendering.py\", line 33, in get_array\n",
      "    self.context.get_cached_data_array(data_hash, binary)\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\serializers\\synchronization_context.py\", line 35, in get_cached_data_array\n",
      "    cache_obj = self.data_array_cache[p_md5]\n",
      "                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n",
      "KeyError: 'b849da5de9259d09deb9c1f88c76b73b_96d'\n",
      "\n",
      "Exception raised\n",
      "KeyError('86e9f7acc6d91363cb2187965a666e3a_75L')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\wslink\\protocol.py\", line 332, in onMessage\n",
      "    results = func(*args, **kwargs)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\protocols\\local_rendering.py\", line 33, in get_array\n",
      "    self.context.get_cached_data_array(data_hash, binary)\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\serializers\\synchronization_context.py\", line 35, in get_cached_data_array\n",
      "    cache_obj = self.data_array_cache[p_md5]\n",
      "                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n",
      "KeyError: '86e9f7acc6d91363cb2187965a666e3a_75L'\n",
      "\n",
      "Exception raised\n",
      "KeyError('3c50750ce4b2a3e58e962921698b0721_66d')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\wslink\\protocol.py\", line 332, in onMessage\n",
      "    results = func(*args, **kwargs)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\protocols\\local_rendering.py\", line 33, in get_array\n",
      "    self.context.get_cached_data_array(data_hash, binary)\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\serializers\\synchronization_context.py\", line 35, in get_cached_data_array\n",
      "    cache_obj = self.data_array_cache[p_md5]\n",
      "                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n",
      "KeyError: '3c50750ce4b2a3e58e962921698b0721_66d'\n",
      "\n",
      "Exception raised\n",
      "KeyError('6208697349b3d6f8cfa89738cc57b836_50L')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\wslink\\protocol.py\", line 332, in onMessage\n",
      "    results = func(*args, **kwargs)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\protocols\\local_rendering.py\", line 33, in get_array\n",
      "    self.context.get_cached_data_array(data_hash, binary)\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\serializers\\synchronization_context.py\", line 35, in get_cached_data_array\n",
      "    cache_obj = self.data_array_cache[p_md5]\n",
      "                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n",
      "KeyError: '6208697349b3d6f8cfa89738cc57b836_50L'\n",
      "\n",
      "Exception raised\n",
      "KeyError('583aa5c6f3363efb739e01acb3687263_66d')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\wslink\\protocol.py\", line 332, in onMessage\n",
      "    results = func(*args, **kwargs)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\protocols\\local_rendering.py\", line 33, in get_array\n",
      "    self.context.get_cached_data_array(data_hash, binary)\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\serializers\\synchronization_context.py\", line 35, in get_cached_data_array\n",
      "    cache_obj = self.data_array_cache[p_md5]\n",
      "                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n",
      "KeyError: '583aa5c6f3363efb739e01acb3687263_66d'\n",
      "\n",
      "Exception raised\n",
      "KeyError('29139bd97c763ebf7cdf9cbf2b85e2fd_50L')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\wslink\\protocol.py\", line 332, in onMessage\n",
      "    results = func(*args, **kwargs)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\protocols\\local_rendering.py\", line 33, in get_array\n",
      "    self.context.get_cached_data_array(data_hash, binary)\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\serializers\\synchronization_context.py\", line 35, in get_cached_data_array\n",
      "    cache_obj = self.data_array_cache[p_md5]\n",
      "                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n",
      "KeyError: '29139bd97c763ebf7cdf9cbf2b85e2fd_50L'\n",
      "\n",
      "Exception raised\n",
      "KeyError('b0a609746e241629e7fddd0e337f9e02_66d')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\wslink\\protocol.py\", line 332, in onMessage\n",
      "    results = func(*args, **kwargs)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\protocols\\local_rendering.py\", line 33, in get_array\n",
      "    self.context.get_cached_data_array(data_hash, binary)\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\serializers\\synchronization_context.py\", line 35, in get_cached_data_array\n",
      "    cache_obj = self.data_array_cache[p_md5]\n",
      "                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n",
      "KeyError: 'b0a609746e241629e7fddd0e337f9e02_66d'\n",
      "\n",
      "Exception raised\n",
      "KeyError('6208697349b3d6f8cfa89738cc57b836_50L')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\wslink\\protocol.py\", line 332, in onMessage\n",
      "    results = func(*args, **kwargs)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\protocols\\local_rendering.py\", line 33, in get_array\n",
      "    self.context.get_cached_data_array(data_hash, binary)\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\serializers\\synchronization_context.py\", line 35, in get_cached_data_array\n",
      "    cache_obj = self.data_array_cache[p_md5]\n",
      "                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n",
      "KeyError: '6208697349b3d6f8cfa89738cc57b836_50L'\n",
      "\n",
      "Exception raised\n",
      "KeyError('35a46a61ae693630a35060ddd7521816_66d')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\wslink\\protocol.py\", line 332, in onMessage\n",
      "    results = func(*args, **kwargs)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\protocols\\local_rendering.py\", line 33, in get_array\n",
      "    self.context.get_cached_data_array(data_hash, binary)\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\serializers\\synchronization_context.py\", line 35, in get_cached_data_array\n",
      "    cache_obj = self.data_array_cache[p_md5]\n",
      "                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n",
      "KeyError: '35a46a61ae693630a35060ddd7521816_66d'\n",
      "\n",
      "Exception raised\n",
      "KeyError('29139bd97c763ebf7cdf9cbf2b85e2fd_50L')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\wslink\\protocol.py\", line 332, in onMessage\n",
      "    results = func(*args, **kwargs)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\protocols\\local_rendering.py\", line 33, in get_array\n",
      "    self.context.get_cached_data_array(data_hash, binary)\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\serializers\\synchronization_context.py\", line 35, in get_cached_data_array\n",
      "    cache_obj = self.data_array_cache[p_md5]\n",
      "                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n",
      "KeyError: '29139bd97c763ebf7cdf9cbf2b85e2fd_50L'\n",
      "\n",
      "Exception raised\n",
      "KeyError('d9366ba611ef3ea4935c03925ec32079_66d')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\wslink\\protocol.py\", line 332, in onMessage\n",
      "    results = func(*args, **kwargs)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\protocols\\local_rendering.py\", line 33, in get_array\n",
      "    self.context.get_cached_data_array(data_hash, binary)\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\serializers\\synchronization_context.py\", line 35, in get_cached_data_array\n",
      "    cache_obj = self.data_array_cache[p_md5]\n",
      "                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n",
      "KeyError: 'd9366ba611ef3ea4935c03925ec32079_66d'\n",
      "\n",
      "Exception raised\n",
      "KeyError('6208697349b3d6f8cfa89738cc57b836_50L')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\wslink\\protocol.py\", line 332, in onMessage\n",
      "    results = func(*args, **kwargs)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\protocols\\local_rendering.py\", line 33, in get_array\n",
      "    self.context.get_cached_data_array(data_hash, binary)\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\serializers\\synchronization_context.py\", line 35, in get_cached_data_array\n",
      "    cache_obj = self.data_array_cache[p_md5]\n",
      "                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n",
      "KeyError: '6208697349b3d6f8cfa89738cc57b836_50L'\n",
      "\n",
      "Exception raised\n",
      "KeyError('0d7820db187a06731f44d0c0c878ec0c_66d')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\wslink\\protocol.py\", line 332, in onMessage\n",
      "    results = func(*args, **kwargs)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\protocols\\local_rendering.py\", line 33, in get_array\n",
      "    self.context.get_cached_data_array(data_hash, binary)\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\serializers\\synchronization_context.py\", line 35, in get_cached_data_array\n",
      "    cache_obj = self.data_array_cache[p_md5]\n",
      "                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n",
      "KeyError: '0d7820db187a06731f44d0c0c878ec0c_66d'\n",
      "\n",
      "Exception raised\n",
      "KeyError('29139bd97c763ebf7cdf9cbf2b85e2fd_50L')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\wslink\\protocol.py\", line 332, in onMessage\n",
      "    results = func(*args, **kwargs)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\protocols\\local_rendering.py\", line 33, in get_array\n",
      "    self.context.get_cached_data_array(data_hash, binary)\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\serializers\\synchronization_context.py\", line 35, in get_cached_data_array\n",
      "    cache_obj = self.data_array_cache[p_md5]\n",
      "                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n",
      "KeyError: '29139bd97c763ebf7cdf9cbf2b85e2fd_50L'\n",
      "\n",
      "Exception raised\n",
      "KeyError('bedb791068030faf29966d6b93e33ed9_1266d')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\wslink\\protocol.py\", line 332, in onMessage\n",
      "    results = func(*args, **kwargs)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\protocols\\local_rendering.py\", line 33, in get_array\n",
      "    self.context.get_cached_data_array(data_hash, binary)\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\serializers\\synchronization_context.py\", line 35, in get_cached_data_array\n",
      "    cache_obj = self.data_array_cache[p_md5]\n",
      "                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n",
      "KeyError: 'bedb791068030faf29966d6b93e33ed9_1266d'\n",
      "\n",
      "Exception raised\n",
      "KeyError('b4ab1a727af184c9d90cef7c99592583_1748L')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\wslink\\protocol.py\", line 332, in onMessage\n",
      "    results = func(*args, **kwargs)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\protocols\\local_rendering.py\", line 33, in get_array\n",
      "    self.context.get_cached_data_array(data_hash, binary)\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\serializers\\synchronization_context.py\", line 35, in get_cached_data_array\n",
      "    cache_obj = self.data_array_cache[p_md5]\n",
      "                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n",
      "KeyError: 'b4ab1a727af184c9d90cef7c99592583_1748L'\n",
      "\n",
      "Exception raised\n",
      "KeyError('86b0ded9c539c340f9a34025c8a76120_1254d')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\wslink\\protocol.py\", line 332, in onMessage\n",
      "    results = func(*args, **kwargs)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\protocols\\local_rendering.py\", line 33, in get_array\n",
      "    self.context.get_cached_data_array(data_hash, binary)\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\serializers\\synchronization_context.py\", line 35, in get_cached_data_array\n",
      "    cache_obj = self.data_array_cache[p_md5]\n",
      "                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n",
      "KeyError: '86b0ded9c539c340f9a34025c8a76120_1254d'\n",
      "\n",
      "Exception raised\n",
      "KeyError('009e2b350ea3f626d26c2d47a8f75a35_1725L')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\wslink\\protocol.py\", line 332, in onMessage\n",
      "    results = func(*args, **kwargs)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\protocols\\local_rendering.py\", line 33, in get_array\n",
      "    self.context.get_cached_data_array(data_hash, binary)\n",
      "  File \"c:\\Python312\\Lib\\site-packages\\trame_vtk\\modules\\vtk\\serializers\\synchronization_context.py\", line 35, in get_cached_data_array\n",
      "    cache_obj = self.data_array_cache[p_md5]\n",
      "                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n",
      "KeyError: '009e2b350ea3f626d26c2d47a8f75a35_1725L'\n",
      "\n"
     ]
    }
   ],
   "source": [
    "mapdl.exit()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
